import Head from "next/head";
import axios from "axios";
import MainPage from "./MainPage";

export default function Home() {
  return (
    <div>
      <Head>
        <title>OP.GG</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainPage />
    </div>
  );
}
