import Head from "next/head";
import MainComponent from "../components/MainComponent";
import axios from "axios";

export default function Home() {
  axios.defaults.baseURL = process.env.REACT_APP_API_URL;
  axios.defaults.withCredentials = true;
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainComponent />
    </div>
  );
}
